name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME_OPERATOR: prometheus-operator
  IMAGE_NAME_CONFIG_RELOADER: prometheus-config-reloader

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker buildx build . --file Dockerfile --platform linux/arm/v7,linux/arm64,linux/amd64 --progress plain
            docker buildx build . --file Dockerfile_config_reloader --platform linux/amd64 --progress plain
          fi

  # Push image to GitHub Package Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Log into registry
        env:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
        run: echo "${password}" | docker login -u ${username} --password-stdin

      - name: Push operator image
        run: |
          IMAGE_ID=cyrilix/$IMAGE_NAME_OPERATOR

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build . --platform linux/arm/v7,linux/arm64,linux/X86_64 --progress plain --push --tag $IMAGE_ID:$VERSION

      - name: Push config_reloader image
        run: |
          IMAGE_ID=cyrilix/$IMAGE_NAME_CONFIG_RELOADER

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker buildx build . -f Dockerfile_config_reloader --platform linux/arm/v7,linux/arm64,linux/amd64 --progress plain --push --tag $IMAGE_ID:$VERSION
